stages:
  - mirror

mirror-repository:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git

    # Configure Git with HTTPS credentials
    - git config --global user.name "${GIT_USER_NAME}"
    - git config --global user.email "${GIT_USER_EMAIL}"

    # Construct authenticated destination repository URL at runtime
    - export AUTHENTICATED_DESTINATION_REPO="https://${GIT_USER}:${GIT_PAT}@${DESTINATION_REPOSITORY}"
    
  script:
    - echo "Cloning repository from source..."
    - git clone --mirror "$SOURCE_REPOSITORY" repo_mirror
    - cd repo_mirror
    - echo "Updating remote origin..."
    - git remote remove origin
    - git remote add origin "$AUTHENTICATED_DESTINATION_REPO"
    - echo "Pushing updates to GitLab..."
    - git push --prune --all
    - git push --prune --tags
  only:
    - branches
