stages:
  - mirror

mirror-repository:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client git expect

    # Ensure SSH directory exists
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Decode and set up SSH private key
    - echo "$GIT_SSH_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Start SSH agent and add private key with password
    - eval $(ssh-agent -s)
    - expect -c "
        spawn ssh-add ~/.ssh/id_rsa
        expect \"Enter passphrase for ~/.ssh/id_rsa:\"
        send \"$GIT_SSH_KEY_PASSWORD\r\"
        expect eof
      "

    # Add GitLab SSH host to known hosts
    - ssh-keyscan git.prometheus.systems >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Force Git to always use SSH instead of HTTPS
    - git config --global url."git@git.prometheus.systems:".insteadOf "https://git.prometheus.systems/"

    # Configure Git user
    - git config --global user.name "${GIT_USER_NAME}"
    - git config --global user.email "${GIT_USER_EMAIL}"
  script:
    - echo "Cloning repository from source..."
    - git clone --mirror "$SOURCE_REPOSITORY" repo_mirror
    - cd repo_mirror
    - echo "Updating remote origin..."
    - git remote remove origin
    - git remote add origin "$DESTINATION_REPOSITORY"
    - echo "Pushing updates to GitLab..."
    - git push --prune --all
    - git push --prune --tags
  only:
    - branches
