stages:
  - mirror

mirror-repository:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client git
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$GIT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan "$GIT_LAB_HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.name "${GIT_USER_NAME}"
    - git config --global user.email "${GIT_USER_EMAIL}"
  script:
    - echo "Cloning repository from source..."
    - git clone --mirror "$SOURCE_REPOSITORY" repo_mirror
    - cd repo_mirror
    - echo "Updating remote origin..."
    - git remote remove origin
    - git remote add origin "$DESTINATION_REPOSITORY"
    - echo "Pushing updates to GitLab..."
    - git push --prune --all
    - git push --prune --tags
  only:
    - branches
